In [52]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.graph_objects as go


from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels,
    prepare_dataframe,
    nice_title,
    save_plotly_fig,
    read_csv_nafix)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [53]:
run_name_prefix = "DKS" # Experiment name. It can be freely chosen.

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary_CL"
sdir.mkdir(exist_ok=True, parents=True)

In [54]:
index_levels_to_drop=["simpl", "clusters", "ll", "opts", "discountrate"] #, , "demand" "sopts"

In [55]:
index_cols = ["run_name_prefix", "run_name", "country", "year", "simpl", "clusters", "ll", "opts", "sopts", "discountrate", "demand", "eopts"]
mean_marginal_prices = read_csv_nafix(sdir / "load_avg_marginal_price.csv", index_col=index_cols)
mean_marginal_prices = drop_index_levels(mean_marginal_prices, index_levels_to_drop)

In [56]:
mean_marginal_prices

                                                                      H2 export bus  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0            NaN
                                                      NH3v0.5+FTv0.5            NaN
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0            NaN
                                                      NH3v0.5+FTv0.5            NaN
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0            NaN
                                                      NH3v0.5+FTv0.5            NaN
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0            NaN
                                                      NH3v0.5+FTv0.5            NaN
                                                      NaN                       NaN

                                                                      FT export bus  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     238.298374
                                                      NH3v0.5+FTv0.5     225.729627
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     235.747716
                                                      NH3v0.5+FTv0.5     222.962824
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     145.013144
                                                      NH3v0.5+FTv0.5     139.022465
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     149.050420
                                                      NH3v0.5+FTv0.5     145.572858
                                                      NaN                       NaN

                                                                      NH3 export bus  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.10_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.11_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.12_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.13_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.14_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.15_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.16_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0      206.132575
                                                      NH3v0.5+FTv0.5      199.698433
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      206.234207
                                                      NH3v0.5+FTv0.5      199.593714
                                                      NaN                        NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0      117.327342
                                                      NH3v0.5+FTv0.5      114.024101
                                                      NaN                        NaN
                                               RF     NH3v1.0+FTv1.0      117.765515
                                                      NH3v0.5+FTv0.5      115.555832
                                                      NaN                        NaN

                                                                      CL.2_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.3_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.4_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.5_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.6_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.7_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.8_1_AC NH3  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575
                                                      NH3v0.5+FTv0.5     199.698433
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     206.234207
                                                      NH3v0.5+FTv0.5     199.593714
                                                      NaN                       NaN
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0     117.327342
                                                      NH3v0.5+FTv0.5     114.024101
                                                      NaN                       NaN
                                               RF     NH3v1.0+FTv1.0     117.765515
                                                      NH3v0.5+FTv0.5     115.555832
                                                      NaN                       NaN

                                                                      CL.9_1_AC NH3
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0     206.132575

## Marginal prices | H2 export price

In [26]:
def set_scen_col(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    scen = df["demand"].map({"RF": "AB", "EL": "AT"})
    # Add export info
    export_info = ""
    # Add export info based on 'eopts', handling NaN and string values
    export_info = df["eopts"].apply(
        lambda x: "50%Exp" if isinstance(x, str) and "v0.5" in x
        else ("NoExp" if pd.isna(x) or str(x) == "" else "100%Exp")
    )
    # Combine
    df["scen"] = scen + export_info.replace("", "", regex=False).apply(lambda x: f"+{x}" if x else "") + df["sopts"].replace("1H", "", regex=False)
    df = df.drop(columns=["eopts", "sopts", "demand"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

In [57]:

df = prepare_dataframe(
    mean_marginal_prices["FT export bus"], 
    idx_slice[["DKS"],:,["CL"],[2030, 2050],["1H"]],
    set_scen_col_name=set_scen_col,
)

#df = df.query("variable in ['FT export bus']")

In [58]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
0,DKS,DKS_CL_2030,AB+100%Exp,2030,CL,FT export bus,235.7
1,DKS,DKS_CL_2030,AB+50%Exp,2030,CL,FT export bus,223.0
3,DKS,DKS_CL_2030,AT+100%Exp,2030,CL,FT export bus,238.3
4,DKS,DKS_CL_2030,AT+50%Exp,2030,CL,FT export bus,225.7
6,DKS,DKS_CL_2050,AB+100%Exp,2050,CL,FT export bus,149.1
7,DKS,DKS_CL_2050,AB+50%Exp,2050,CL,FT export bus,145.6
9,DKS,DKS_CL_2050,AT+100%Exp,2050,CL,FT export bus,145.0
10,DKS,DKS_CL_2050,AT+50%Exp,2050,CL,FT export bus,139.0

In [60]:
[df.loc[(df.scen == "AT+50%Exp") & (df.country == "CL")]["value"].values[0]]

[225.7]

In [61]:
def marginal_price_dumbbell_fig(df, year, data_start="0.1MtH2export", data_mid="0.4MtH2export",data_end="0.7MtH2export"):

    df = df.copy()

    df = df[df.year==year]
    countries = df.sort_values(by=["value"], ascending=False)["country"]

    data = {"line_x": [], "line_y": [], 
            "data_start": [], "data_mid": [], "data_end": [], 
            "colors": [], "years": [], "countries": []}

    for country in countries:
        data["data_start"].extend([df.loc[(df.scen == data_start) & (df.country == country)]["value"].values[0]])
        data["data_mid"].extend([df.loc[(df.scen == data_mid) & (df.country == country)]["value"].values[0]])
        data["data_end"].extend([df.loc[(df.scen == data_end) & (df.country == country)]["value"].values[0]])
        data["line_x"].extend(
            [
                df.loc[(df.scen == data_start) & (df.country == country)]["value"].values[0],
                df.loc[(df.scen == data_end) & (df.country == country)]["value"].values[0],
                None,
            ]
        )
        data["line_y"].extend([country, country, None]),

    fig = go.Figure(
        data=[
            go.Scatter(
                x=data["line_x"],
                y=data["line_y"],
                mode="lines",
                showlegend=False,
                marker=dict(
                    color="grey"
                )
            ),
            go.Scatter(
                x=data["data_start"],
                y=countries,
                mode="markers+text",
                name=data_start,
                text=data["data_start"],            
                textposition="top left",
                texttemplate="%{text:.1f}",
                textfont=dict(size=11),
                marker=dict(
                    color="#A6BCC9",
                    size=13
                )

            ),
            # go.Scatter(
            #     x=data["data_mid"],
            #     y=countries,
            #     mode="markers",
            #     name=data_start,
            #     marker=dict(
            #         color="#6C9DB9",
            #         size=13
            #     )

            # ),
            go.Scatter(
                x=data["data_end"],
                y=countries,
                mode="markers+text",
                name=data_end,
                text=data["data_end"],
                textposition="top right",
                texttemplate="%{text:.1f}",
                textfont=dict(size=11),
                marker=dict(
                    color="#179c7d",
                    size=13
                )
            ),
        ]
    )

    fig.update_layout(
        title=dict(text=nice_title(f"Marginal price for H2 at export port in {year}", 
                                   "Per country and H2 export volume in €/MWh_H2_LHV")),
        width=800,
        height=500,
        legend_itemclick=False
    )
    return fig

In [63]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
0,DKS,DKS_CL_2030,AB+100%Exp,2030,CL,FT export bus,235.7
1,DKS,DKS_CL_2030,AB+50%Exp,2030,CL,FT export bus,223.0
3,DKS,DKS_CL_2030,AT+100%Exp,2030,CL,FT export bus,238.3
4,DKS,DKS_CL_2030,AT+50%Exp,2030,CL,FT export bus,225.7
6,DKS,DKS_CL_2050,AB+100%Exp,2050,CL,FT export bus,149.1
7,DKS,DKS_CL_2050,AB+50%Exp,2050,CL,FT export bus,145.6
9,DKS,DKS_CL_2050,AT+100%Exp,2050,CL,FT export bus,145.0
10,DKS,DKS_CL_2050,AT+50%Exp,2050,CL,FT export bus,139.0

In [ ]:
fig = marginal_price_dumbbell_fig(df, 
                                  year=2050, 
                                  data_start="AT+50%Exp", 
                                  data_mid="AT+50%Exp",
                                  data_end="AT+100%Exp")

fig.show()

IndexError: index 0 is out of bounds for axis 0 with size 0

In [34]:
fig = marginal_price_dumbbell_fig(df, year=2035, 
                                  data_start="0.1MtH2export", 
                                  data_mid="0.4MtH2export",
                                  data_end="0.7MtH2export")

fig.show()

KeyError: 'value'